nama = input("Nama                  : ")
NIM = input("NIM                   : ")
kls = input("Kelas Paralel         : ")
TTL = input("Tempat/Tanggal Lahir  : ")
Alamat =  input("Alamat                : ")
Hobby = input("Hobby                 : ")
No = input("No. HP                : ")

print("Nama                  : " +nama)
print("NIM                   : " +NIM)
print("Kelas Paralel         : " +kls)
print("Tempat/Tanggal Lahir  : " +TTL)
print("Alamat                : " +Alamat)
print("Hobby                 : " +Hobby)
print("No. HP                : " +No)